[package]
name = "maiewsldsa"
version = "0.1.0"
authors = ["john <junchen@151.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]



[lib]
crate-type=["staticlib", "cdylib"]
